### ISSUE TITLE
Stages cost calculation

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#1]
### Description
For closure report due each stage, we need to calculate costs

### TODO
- [ ] Calculate spent resources for Initiation stage
- [ ] Calculate spent resources for 1st Subsequent stage
- [ ] Calculate spent resources for 2nd Subsequent stage
- [ ] Calculate spent resources for Closure stage

**Comment by RJSkudra** [comment]
@LBTU-IT-M24/development-team get a notification

**Comment by RJSkudra** [comment]
test 2

**Comment by RJSkudra** [comment]
@dianabobriseva Isn't this a duplicate of  #113 ?
