### ISSUE TITLE
Each stage current costs/expenses calculation

### ISSUE THREAD

**Issue by dianabobriseva** [LBTU-IT-M24/ClassMate#113]
### Description
To define current budget state and in case alert risk management about budget overrun.

### TODO

- [ ] Calculate pre-project stage total costs 
- [ ] Calculate project initiation stage total costs 
- [ ] Calculate 1st Subsequent stage total costs
- [ ] Calculate 2nd Subsequent stage total costs
- [ ] Create end costs calculations
