### ISSUE TITLE
UI Wireframe development

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#15]
### Description
Since we have a description of the project, we can start developing wireframe for ClassMate project

### TODO
- Create a wireframe for future ClassMate project according to SRS
    - [x] Include all 7 main tools mentioned in Project Brief
    - Make wireframe for following ClassMate pages:
        - [x] Authorization screen
        - [x] Home screen with closed component sidebar
        - [x] Home screen with opened component sidebar
---
## RESULTS & logged time
- Design research (1h)
-  ### Information Architecture - Site Map (0,5h)

> ![Image](https://github.com/user-attachments/assets/28694b8f-42e4-488c-bb08-d8e2131ae571)

- ### Wireframes - Low fidelity WF (0,5h)

> ![Image](https://github.com/user-attachments/assets/1caa220e-efbe-4d41-9815-fbbf58949fd9)

- ### [Wireframes -High fidelity WF](https://miro.com/app/board/uXjVLZ1aGNc=/?share_link_id=448998913599) (1 + ... h)
![Image](https://github.com/user-attachments/assets/763da99f-ad94-4cb7-b20e-64054f885ddc)

- - ### BrainStorm Board 
- - - [Link to commented WF](https://wireframe.cc/wXUljr) 
 
@LBTU-IT-M24/design-team

**Comment by RJSkudra** [comment]
@mesahil321

**Comment by kitten-cake-png** [comment]
Please review WF: [Click here](https://miro.com/app/board/uXjVLZ1aGNc=/?share_link_id=448998913599) 
@andrejste7

**Comment by kitten-cake-png** [comment]
@andrejste7 I have updated the UI component design [please see the 4th page bottom.](https://xd.adobe.com/view/425ed16a-3db9-42d2-b2d2-cb90ec35571c-170d/screen/ca80c356-b878-4a1e-9207-124db80d7748). There should be:

- Modular window sample with no tabs.
- 2 variations of element cards sample.

Please take notice, that I've added only for better visabilty some shadow drop for some parts. Its only for cosmetic reasons! Not to be programmed (atleast not yet 😆 ). Comments left on [WF are resolved](https://miro.com/app/board/uXjVLZ1aGNc=/). Please open a new comment box if need. 

Comment updates AdobeXD on:

- Pagination

Pending from @kitten-cake-png & friends:

- [ ] Mockup first version
- [ ] Design review
- [ ] Adjustments
- [ ] High fidelity mockup
- [ ] Design acceptence

**Comment by kitten-cake-png** [comment]
Please do a acceptence testing @SandisAbele for the provided [WF](https://miro.com/app/board/uXjVLZ1aGNc=/)

**Comment by SandisAbele** [comment]
Reviewed it: Looks good - flow is clear and understandable, features are well defined too, approved. @kitten-cake-png
