### ISSUE TITLE
Timer/Stopwatch component development

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#18]
### Description
Implement a component that would allow user to start a timer and manage stopwatch (with an option to switch between timer and stopwatch)

### TODO
- [ ] Implement component described above

**Comment by andrejste7** [comment]
What to test?

- [ ] Check if component works as expected
- [ ] Check if configuration changes are possible to be made

**Comment by SandisAbele** [comment]
Tested:

![firefox_LLSwcwPPp7](https://github.com/user-attachments/assets/ed292f3f-5c2a-4bf2-b43b-50a9a88a6c42)

Seems like there is a bug regarding the timer running out and setting another value, it is offset by the time that just ran out, i.e - If i set the timer to 00:00:05 (5sec) and let it run out, works fine, but when I try to set it to 5sec again, it shows me that it's set to 00:00:00.

Likewise I imagine this happens with any time-frame running out.

Returning to DEV @arturslast 

p.s might be worth while having some noise or ding when it stops, to notify the user.

**Comment by arturslast** [comment]
@SandisAbele can be re-tested in test branch. Added sound on times-up

**Comment by SandisAbele** [comment]
Retested:

Seems like there is a bug with the "Font Size" slider -> It doesn't really do anything

![firefox_eTBVfOQFW9](https://github.com/user-attachments/assets/c7d19b37-15e5-41be-bb40-3422d2de0342)

Returning to DEV @LabaisLatvietis

**Comment by LabaisLatvietis** [comment]
Do the thing

**Comment by SandisAbele** [comment]
Retested

Font size now does change the actual number size the timer/stopwatch displays. Other features were tested before and work as expected.

QA Pass.
