### ISSUE TITLE
Clock component development

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#19]
### Description
According to project brief, we need to create a personal digital workspace components. We need a round clock component that would be drag-n-drop-able and configurable.

### TODO
- [x] Implement component described above

**Comment by andrejste7** [comment]
What to test?

- [ ] Check if component works as expected
- [ ] Check if configuration changes are possible to be made

**Comment by SandisAbele** [comment]
Tested:

Clock can be modified (Transparency/Font size for text/Bg color), don't see any unexpected behaviors, time displayed itself is also accurate.

QA pass, closing the ticket.

**Comment by LabaisLatvietis** [comment]
Labota teksta izmēru maiņa
