### ISSUE TITLE
UI mockup development

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#20]
### Description
After developing wireframes for ClassMate, we can start defining color schemes and component design

### TODO
- [x] Based on UI wireframes, create mockups for end version of ClassMate project

---
#### Estimated hours
- Identity (Color Pallete, Typography, UI elements) (1h)
- Low fidelity (2h)
- Review (0,5h)
- High fidelity (2h)
- Review (0,5)
- Possible edits (1h)

@LBTU-IT-M24/design-team

**Comment by kitten-cake-png** [comment]
Pending from @kitten-cake-png & friends:

- [ ] Mockup first version
- [ ] Design review
- [ ] Adjustments
- [ ] High fidelity mockup
- [ ] Design acceptence

**Comment by kitten-cake-png** [comment]
Final aceppted @andrejste7 mocukps are avalible here: [click](https://xd.adobe.com/view/92deba9e-b0e7-4df6-8705-71db4bc6c7d1-c78d/grid )

**Comment by RJSkudra** [comment]
@kitten-cake-png Can we close this issue then?
