### ISSUE TITLE
Json server setup for storing data

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#25]
### Description
To store component data and user preferences/setting, we need a dedicated place to do so

### TODO
- [ ] Explore JSON server capabilities
- [ ] Setup one for ClassMate project
- [ ] Prepare a documentation on how to use it

**Comment by RJSkudra** [comment]
Out of scope
