### ISSUE TITLE
Docker container creation

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#27]
### Description
To ship/deliver our project to any desired server without extra effort and headache, we should use docker for that

### TODO

- [x]  Explore docker documentation
- [x] Create a GitHub action that automatically creates a Docker image
- [x] Create a docker-compose file with corresponding setup
