### ISSUE TITLE
Work package “PRINCE2 documents” writing

### ISSUE THREAD

**Issue by dianabobriseva** [LBTU-IT-M24/ClassMate#45]
### Description
Since all PRINCE2 document requirements are known, document writing tasks should be summed up in work package.

### TODO:

- [x] Write work package description
- [x] Define requirements and quality criteria
- [x] Define constraints
- [x] Define dependencies according to tasks on GitHub
- [x] Define reporting and control method
