### ISSUE TITLE
Work package “Software” writing

### ISSUE THREAD

**Issue by dianabobriseva** [LBTU-IT-M24/ClassMate#46]
### Description
Since software requirements are known, software development tasks should be summed up in work package.

### TODO:

- [x] Write work package description
- [x] Define requirements and quality criteria
- [x] Define constraints
- [x] Define dependencies according to tasks on GitHub
- [ ] Define reporting and control method
