### ISSUE TITLE
Highlight report writing

### ISSUE THREAD

**Issue by dianabobriseva** [LBTU-IT-M24/ClassMate#47]
### Description
Since tasks are created and assigned, should be created a report about task completion in development stages.

### TODO:
- [ ] Description of Work - Defines the tasks or deliverables to be completed.
- [ ] Requirements and Quality Criteria - Specifies what is required and the quality standards.
- [ ] Constraints - Outlines any limits like time, cost, or resources.
- [ ] Team and Responsibilities - Identifies who is responsible for the work.
- [ ] Dependencies - Lists any work that relies on other tasks or packages.
- [ ] Reporting and Control - Defines how progress will be monitored and reported.

**Comment by AbhiSph** [comment]
[Highlight Report.docx](https://github.com/user-attachments/files/17444445/Highlight.Report.docx)

**Comment by RJSkudra** [comment]
The link was gotten from 19.10.2024 meeting: https://docs.google.com/document/d/12OIJwAzmhRyPTUfozbxP-n10FUAZ6yr46vxjDW6dtDI/edit?pli=1&tab=t.0#heading=h.phqa6vbymowo

**Comment by RJSkudra** [comment]
Reviewed. If we can still change the document structure then I have left comments in the document and here is a short things to do based on what is done:

**TODO**

- [ ] Fix formatting issues with the text having huge spaces
- [ ] Update the time log when everyone has updated their time (24.10.24)
