### ISSUE TITLE
Stage Plan preparation for development stage

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#5]
### Description
To start a development cycles running in outsourcing company, we need a development stage plan

### TODO
- Create a Stage Plan consisting of:
    - [x] Stage Objectives - Clear goals for the stage
    - [x] Scope - What is included and excluded in the stage
    - [x] Schedule - Detailed timeline and milestones
    - [x] Resources - Required resources and their allocation
    - [x] Budget - Planned costs and financial management
    - [x] Quality - Quality criteria and control measures
    - [x] Risks - Identified risks and mitigation strategies for the stage
    - [x] Communication Plan - How information will be communicated during the stage
    - [x] Dependencies - Dependencies on other stages or external factors
    - [x] Acceptance Criteria - Criteria for accepting the deliverables of the stage

**Comment by andrejste7** [comment]
How roles could be separated:
![Image](https://github.com/user-attachments/assets/dffb58bd-a8e6-40ab-8e95-bc13f1c50057)

**Comment by KristineIvanova** [comment]
Stage plan created.
