### ISSUE TITLE
Setup GitHub Pages for Test and Main branch

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#86]
Due to GitHub limitations only a single branch of the Repo can be used to build and deploy a GitHub Page. Testers need to test the Test branch GitHub Page and afterwards changes must be pushed to Main, but for demo purposes a Main branch GitHub Page is also needed.

**TODO**

- (workaround found) Test mirroring test branch in another Repo?
- [x] Find a workaround in main Repo?
- [ ] Implement the solution
- [ ] Inform the changes to QA and Dev teams

**Comment by RJSkudra** [comment]
A workaround was found, so mirroring the repo to make a new GitHub page is not necessary.
