### ISSUE TITLE
Look over Repo ruleset

### ISSUE THREAD

**Issue by RJSkudra** [LBTU-IT-M24/ClassMate#87]
The GitHub repository needs a ruleset that doesn't allow rogue force pushes to main branch. Other safety features need to be looked over and evaluated if they harm the development or organize the workflow better.

**TODO**

- [x] Read the GitHub documentation on [rulesets](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets) 
- [x] Talk with Dev team about which rules would benefit their workflow
- [x] Test specific rules
- [x] Implement and document changes
